version: "3.7"

services:
  memoryflash_db:
    image: postgres
    container_name: memoryflash_db
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  memoryflash_api:
    build: .
    container_name: memoryflash_api
    ports:
      - 3334:3334
    volumes:
      - .:/home/node/server
    network_mode: host

  memoryflash_redis:
    image: redis:alpine
    env_file:
      - .env
    environment:
      REDIS_MASTER_HOST: ${REDIS_HOST}
      REDIS_PORT_NUMBER: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    network_mode: host

volumes:
  pgdata:
    driver: local