version: "3.7"

services:
  memoryflash_db:
    image: postgres
    container_name: memory-flash-db
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  memoryflash_api:
    build: .
    container_name: memoryflash-api
    ports:
      - 3334:3334
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local